name: fboss
version: 0.1.0
vendor: Kyle Fazzari <kyle@canonical.com>
summary: Facebook Open Switching System
description: Facebook's software stack for controlling and managing network switches
icon: icon.svg

parts:
  folly:
    plugin: autotools
    source: https://github.com/facebook/folly.git
    source-type: git
    source-subdir: folly
    build-packages:
      - libtool
      - libboost-all-dev
      - libevent-dev
      - libdouble-conversion-dev
      - libgoogle-glog-dev
      - libgflags-dev
      - liblz4-dev
      - liblzma-dev
      - libsnappy-dev
      - zlib1g-dev
      - binutils-dev
      - libjemalloc-dev
      - libssl-dev
      - libiberty-dev

    stage-packages:
      - libboost-atomic1.54.0
      - libboost-chrono1.54.0
      - libboost-date-time1.54.0
      - libboost-filesystem1.54.0
      - libboost-iostreams1.54.0
      - libboost-program-options1.54.0
      - libboost-python1.54.0
      - libboost-regex1.54.0
      - libboost-serialization1.54.0
      - libboost-system1.54.0
      - libboost-thread1.54.0

      - libevent-2.0-5
      - libevent-core-2.0-5
      - libevent-extra-2.0-5
      - libevent-pthreads-2.0-5
      - libevent-openssl-2.0-5

      - libdouble-conversion1
      - libgoogle-glog0

      - libgflags2

      - liblz4-1

      - liblzma5

      - libsnappy1

      - zlib1g

      - binutils

      - libjemalloc1

      - libssl1.0.0

  wangle:
    plugin: cmake
    source: https://github.com/facebook/wangle.git
    source-type: git
    source-subdir: wangle
    after: [folly]

  fbthrift:
    plugin: autotools
    configflags:
      # This is the only way to get this thing to install in a place other than /lib/python.
      # Obviously change it to fit the situation.
      - "PY_INSTALL_HOME=/home/ubuntu/src/fboss-snap/parts/fbthrift/install"
    source: https://github.com/facebook/fbthrift.git
    source-type: git
    source-subdir: thrift
    after: [folly, wangle]
    build-packages:
      - flex
      - bison
      - pkg-config

      - libkrb5-dev
      - libsasl2-dev
      - libnuma-dev
      - libssl-dev

    stage-packages:
      - libkrb5-3
      - libk5crypto3
      - libgssapi-krb5-2
      - libgssrpc4
      - libkadm5srv-mit9
      - libkadm5clnt-mit9
      - libcomerr2
      - libasn1-8-heimdal
      - libgssapi3-heimdal
      - libhcrypto4-heimdal
      - libhdb9-heimdal
      - libheimbase1-heimdal
      - libhx509-5-heimdal
      - libkadm5clnt7-heimdal
      - libkadm5srv8-heimdal
      - libkafs0-heimdal
      - libkdc2-heimdal
      - libkrb5-26-heimdal
      - libwind0-heimdal
      - libotp0-heimdal
      - libsl0-heimdal
      - libroken18-heimdal
      - heimdal-clients

      - libsasl2-2

      - libnuma1

      - libssl1.0.0

      - zlib1g

  iproute:
    plugin: autotools
    source: https://www.kernel.org/pub/linux/utils/net/iproute2/iproute2-3.19.0.tar.xz
    build-packages:
      - libdb5.3-dev

    stage-packages:
      - libdb5.3

  # OpenNSL has no build system-- it's distributed precompiled. That's not a
  # use-case really supported by Snapcraft, so we wrote our own Makefile to
  # deal with it.
  opennsl:
    plugin: make
    source: opennsl

  # This builds fine, but it won't install as fboss doesn't specify a single
  # install rule. In fact, some of its tools require sed hacks to even setup,
  # so this may require a custom plugin.
  fboss:
    plugin: cmake
    source: https://github.com/facebook/fboss.git
    source-type: git
    after: [folly, fbthrift, iproute, opennsl]
    configflags:
      # For some reason iproute doesn't install the required libs, so we need to
      # use it from where it was built instead.
      - -DCMAKE_LIBRARY_PATH=/home/ubuntu/src/fboss-snap/parts/iproute/build/lib

    build-packages:
      - libpcap0.8-dev
      - libusb-1.0-0-dev

    stage-packages:
      - libpcap0.8
      - libusb-1.0-0
